### ISSUE TITLE
Update text in `README.md` file 

### ISSUE THREAD

**Issue by ahernank** [SoniaBarasa/country-capital-quiz-game#14]
Currently the text reads: `This is a fun game in which the players take turns to guess capital cities of different countries in the world . main`. It would be good to update this to not have the `. main` for clarity. 

I would suggest doing this through a PR (in the same way we have been doing for files with python code - create a branch and edit the file using your local IDE) instead of using the edit feature in the repository website.

**Comment by SoniaBarasa** [comment]
Thanks @ahernank .I will close this issue, It was a simple edit that I did on the main branch.
