### ISSUE TITLE
Change repository name

### ISSUE THREAD

**Issue by alimanfoo** [SoniaBarasa/country-capital-quiz-game#4]
I'd suggest to change the name of this GitHub repo to something a little more specific, e.g., "CapitalQuizGame" or something like that. This might help later on when you have lots of repositories in your GitHub user account.

**Comment by SoniaBarasa** [comment]
Thank you @alimanfoo for the suggestion, I have renamed the repository to country-capital-quiz-game, so I am going to close this issue.
