### ISSUE TITLE
Add more countries and capitals

### ISSUE THREAD

**Issue by alimanfoo** [SoniaBarasa/country-capital-quiz-game#6]
It would be cool if this game included all countries in the world. That way it would be a real challenge, as I'm sure not everyone knows all the capitals of all the countries!

This might be a good opportunity to use a third-party package, rather than try to manually add all the countries and capitals within the source code for the game. E.g., the [pycountry](https://pypi.org/project/pycountry/) package provides a list of all countries in the world, and the [countryinfo](https://github.com/porimol/countryinfo) package has capital cities for all countries.

**Comment by alimanfoo** [comment]
Hi @SoniaBarasa, this might be one to tackle a bit later on, because it would require setting up your project to handle dependencies on other Python packages. But thought I would create the issue now before I forget 🙂

**Comment by SoniaBarasa** [comment]
Thank you Alistair! that would make the game more interesting actually with many options to choose from as well as game iterations!

**Comment by SoniaBarasa** [comment]
Hi folks, am going to close this issue since its been resolved by pull request #15
